- name: Update webpage
  hosts: all
  gather_facts: false

  tasks:
          
  - name: Update Index Page for webpage
    template:
      src: indexcomplex.html.j2
      dest: /var/www/html/index.html